apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-nuly
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-nuly@sha256:3b066ff0b22072243238add9445c8d70a97fa4187c37f8049a770507bbd589be
        name: my-nodejs
        resources: {}
status: {}
